# Generated by Django 2.2.7 on 2019-11-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
    ]
