# Generated by Django 2.2.7 on 2019-11-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0004_auto_20191122_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='check_in_time',
            field=models.TimeField(auto_now_add=True, verbose_name='Check in time'),
        ),
    ]
