# Generated by Django 2.2.7 on 2019-11-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0005_auto_20191122_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='check_in_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Check in time'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='check_out_time',
            field=models.DateTimeField(null=True, verbose_name='Check out time'),
        ),
    ]
